### ISSUE TITLE
Kernel panic when change #ifdef __FAKE__

### ISSUE THREAD

**Issue by kayakaantuna** [TechNexion-Vision/jetson_technexion-bsp#1]
Hello,

I'm using your camera driver which you wrote for ap1302 in Jetson Nano 4GB. I want to get my boot data registers from header file so I switch #ifdef __FAKE__ to #ifndef __FAKE__ to get the data from bootdata.h. However when I do that it enters to kernel panic mode with the following error:

Kernel panic - not syncing: Aiee, killing interrupt handler!
SMP: stopping secondary CPUs
Kernel Offset: disabled
Memory Limit: none

Do you have any idea why this happens ? It would be great, if you can provide some support.

Thanks

**Comment by shuwn** [comment]
Hi, @kayakaantuna 
Could you please provide the product order number, so that we can arrange for FAE to help you.
Thank you!

**Comment by kayakaantuna** [comment]
Hi, @shuwn 

I'm using On semi conductors ap1302, not yours. However I did fix the issue.
This line caused the issue:
priv->header = priv->otp_flash_instance->header_data;

So thanks anyways.

Furthermore, there is a new issue, which is when I try to read 0x6002 it returns 0xffff. I'm not sure you can help with this or not since its not your product really. But thanks anyways.

**Comment by mars9820** [comment]
Hi,

This repro is for support of TechNexion embedded vision products.
