### ISSUE TITLE
Support for AR0234 with Orin NX

### ISSUE THREAD

**Issue by alexispap51** [TechNexion-Vision/jetson_technexion-bsp#2]
### Description
I am currently facing an issue with the compatibility of two AR0234 sensors with the Jetson Orin NX carrier board. While the Jetson Orin NX is supposed to support these sensors, I am unable to locate the necessary scripts in the TechNexion Vision GitHub repository, specifically in the [TEV-Jetson_Jetpack_script](https://github.com/TechNexion-Vision/TEV-Jetson_Jetpack_script) repository.

### Details

- **Hardware**
  - [Forecr](https://www.forecr.io/products/carrier-board-dsboard-ornx?variant=46593316028765) Jetson Orin NX Carrier Board
  - 2x [TEVI-AR0234](https://www.technexion.com/products/embedded-vision/mipi-csi2/tevi-ar0234/)

**Comment by jigoku1206** [comment]
Hi @alexispap51 

Have you resolved this issue?
