### ISSUE TITLE
Issue with Auto exposure ar0234 flicker at day time at 60 fps

### ISSUE THREAD

**Issue by Shree-96** [TechNexion-Vision/jetson_technexion-bsp#3]
Hi, We are using sensor TEVI-ar0234 with Jetson Xavier NX. We are using current v4l2-ctl driver and with width=1920, height=1080, fps=60. There is very constant fluctuation when camera is in auto exposure. Do you guys know what could be the issue.

![Screenshot from 2024-02-02 11-17-43](https://github.com/TechNexion-Vision/TEV-Jetson_Camera_driver/assets/156793348/270ff975-9234-4dbb-bf3c-ecc0ef0a9dbc)
![Screenshot from 2024-02-02 11-17-36](https://github.com/TechNexion-Vision/TEV-Jetson_Camera_driver/assets/156793348/ca990080-7083-48b1-95c1-01c904b399a5)
![Screenshot from 2024-02-02 11-17-33](https://github.com/TechNexion-Vision/TEV-Jetson_Camera_driver/assets/156793348/65c11abb-3ab6-4f7a-948b-0b3f1e383f07)
![Screenshot from 2024-02-02 11-17-32](https://github.com/TechNexion-Vision/TEV-Jetson_Camera_driver/assets/156793348/b408e917-0bd3-4fdf-886a-c5609011b109)
![Screenshot from 2024-02-02 11-17-30](https://github.com/TechNexion-Vision/TEV-Jetson_Camera_driver/assets/156793348/8cb99b25-24c1-4f1f-afc3-ba729c1e3be0)

**Comment by jigoku1206** [comment]
Hi @Shree-96 ,
Could you provide a video for this problem? I cannot clarify your issue from your images.

**Comment by Shree-96** [comment]
[Screencast.webm](https://github.com/TechNexion-Vision/TEV-Jetson_Camera_driver/assets/156793348/5a4a98d3-00bd-442b-a245-c2bea598d5c1)

This is the video of AR0234 at day time with 60fps.

**Comment by jigoku1206** [comment]
Hi @Shree-96 ,

We need to confirm something about your case. I think the problem is possibly caused by "FPS" setting. If you use 2-lane setting, the camera cannot achieve 60 fps, you can modify the fps to 30 fps then try it again.
