### ISSUE TITLE
Issue with Auto exposure ar0234 flicker at day time at 60 fps

### ISSUE THREAD

**Issue by Shree-96** [TechNexion-Vision/jetson_technexion-bsp#4]
Hi, 
We are using sensor TEVI-ar0234 with Jetson Xavier NX. We are using current v4l2-ctl driver and with width=1920, height=1080, fps=60. There is very constant fluctuation when camera is in auto exposure. Do you guys know what could be the issue.
[Screencast.webm](https://github.com/TechNexion-Vision/TEV-Jetson_Camera_driver/assets/156793348/08e77506-875f-46ab-97b5-1c1c64234395)

Thank you for your help.

**Comment by jigoku1206** [comment]
I have replied to you at #3
