### ISSUE TITLE
Getting wrong Address for AR0521 and Ar0821 

### ISSUE THREAD

**Issue by Shree-96** [TechNexion-Vision/jetson_technexion-bsp#5]
We are connecting Tevi-AR0521 and Tevi-AR0821 which are 2-lane camera to Dev KIt of Xavier NX.
we are getting ‘3c’ address on i2c-bus instead of ‘3d’.  Where We are getting correct address with Tevi-AR0234.
sudo i2cdetect -y -r 2
0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: – – – – – – – – – – – – –
10: – – – – – – – – – – – – – – – –
20: – UU – – – – – – -- – – – – – – –
30: – – – – – – – – – – – – 3c – – –
40: -- – – – UU – – – – – – – – – – –
50: – – – – UU UU – – – – – – – – – –
60: – – – – – – – – – – – – – – – –
70: – – – – – – – –

**Comment by jigoku1206** [comment]
Hi @Shree-96 ,

I am sorry I don't have Xavier NX DevKit currently.
Then I cannot replicate your problem on Jetson Nano DevKit.
I can probe successfully for TEVI-AR0234, TEVI-AR0521, and TEVI-AR0821 on Jetson Nano DevKit.

```
# i2cdetect -r -y 8
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- UU -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- UU -- --
40: UU -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- UU UU -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- 6a -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

Could you amend the i2c frequency to 100K and try it again?

**Comment by jigoku1206** [comment]
Hi @Shree-96 

By the way, do you share your SW configuration for TEV-RPI15 adaptor?
I think maybe the configuration is wrong.

**Comment by Shree-96** [comment]
Hi @jigoku1206,
We have done same changes in PRI adaptor settings as shown in below links.
https://www.technexion.com/shop/embedded-vision/mipi-csi2/tevi-ar0521-c/
https://www.technexion.com/shop/embedded-vision/mipi-csi2/tevi-ar0821-c/

We don;t have any Jetson-Nano Devkit for now we will arrange and test and let you know.

Thank you.
